# -*- coding: utf-8 -*-
"""ippi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRzIK_e3TbhQRck6onp6I27LJ4GHlFcC
"""

from flask import Flask, request, jsonify, render_template
import joblib
from pyforest import *

#naming our app as app
app= Flask(__name__)

#loading the pickle file for creating the web app
model= joblib.load(open("model.pkl", "rb"))

@app.route("/")
def home():
    return render_template("new11.html")

@app.route("/predict", methods=["POST"])
def predict():
    int_features= [float(x) for x in request.form.values()]
    final_features= [np.array(int_features)]
    prediction= model.predict(final_features)
    output= round(prediction[0], 2)
    return render_template("new11.html", prediction_text= "cab price is {}".format(output))

#running the flask app
if __name__ == "__main__" :
    app.run(debug=True)

